"""commission_structure_overhaul

Revision ID: cd1d80f67c8d
Revises: 
Create Date: 2026-07-29 23:23:40.951376

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'cd1d80f67c8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'crm_customers', 'staff', ['preferred_staff_id'], ['id'])
    op.drop_index('merchant_id', table_name='fee_policies')
    op.create_unique_constraint('uq_fee_policies_merchant_id', 'fee_policies', ['merchant_id'])
    op.create_foreign_key(None, 'settlements', 'users', ['sales_manager_user_id'], ['id'])
    op.alter_column('staff', 'share_rate',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               nullable=False,
               existing_server_default=sa.text('0.5000'))
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.alter_column('staff', 'share_rate',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               nullable=True,
               existing_server_default=sa.text('0.5000'))
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.drop_constraint('uq_fee_policies_merchant_id', 'fee_policies', type_='unique')
    op.create_index('merchant_id', 'fee_policies', ['merchant_id'], unique=True)
    op.drop_constraint(None, 'crm_customers', type_='foreignkey')
    # ### end Alembic commands ###
